import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@radix-spectrum/components/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Turborepo",
    description: "Generated by create turbo",
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
    return (
        <html className="spectrum spectrum--medium" lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
